# Numpy Part -1

In [1]:
import numpy as np

### 1. Numpy 배열(N-Dimensional Array)

In [2]:
a = np.array([1,3,4,7], float)

In [3]:
a

array([1., 3., 4., 7.])

In [4]:
a.dtype, a.shape, a.ndim, a.size

(dtype('float64'), (4,), 1, 4)

In [5]:
# Vector(1차원)
a = np.array([1,3,4,7], float)
a


array([1., 3., 4., 7.])

In [6]:
# Matrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [7]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [8]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [10]:
np.array([1,2,3,4], dtype = np.uint8)

array([1, 2, 3, 4], dtype=uint8)

In [11]:
# reshape
c.size

24

In [12]:
c.reshape(4,6) # size가 같으면 reshape 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
c.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
c.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
a.reshape(4,-1)

array([[1.],
       [3.],
       [4.],
       [7.]])

In [16]:
a.reshape(-1,4)


array([[1., 3., 4., 7.]])

In [17]:
# shape은 튜플
b.reshape(-1,)

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

In [18]:
b.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing

In [19]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a[1][1], a[1][1], a[-1,-2]

(5, 5, 5)

In [21]:
a[1,:2]

array([4, 5])

In [22]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [23]:
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [24]:
b[:2,1:], b[1:,:2]

(array([[2, 4],
        [3, 9]]),
 array([[4, 3],
        [3, 7]]))

In [25]:
b[:2, ::2]

array([[1, 4],
       [4, 9]])

#배열 생성

In [26]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(1,4.1,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [29]:
l = np.arange(1,4.1,0.5).tolist()
l

[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]

In [30]:
np.arange(-2,2.01,0.02).size

201

In [31]:
# linear space
np.linspace(-2,2,201).size

201

-oncs, zeros, empty

In [33]:
np.ones(shape = (10, ), dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [34]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.zeros(4)

array([0., 0., 0., 0.])

In [37]:
np.empty(4)  #공간만

array([0., 0., 0., 0.])

- 대각선 : identity, eye

In [39]:
# 정방형 ( n x n)
np.identity(3, dtype = np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [40]:
#직사각형 모양 ( N X M)
np.eye(N = 3, M = 5, dtype = np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int16)

In [42]:
np.eye(3,5,k = 1, dtype = np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

- 데이터 분포에 따른 random sampling

In [43]:
np.random.seed(2021)

In [44]:
np.random.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])

In [45]:
np.random.normal(10,4,4)

array([12.22350333,  7.17798285, 14.52343305, 12.58000735])

In [46]:
#표준 정규분포
np.random.randn(4)   #np.random.normal(0,1,4)


array([ 0.10641374,  0.42215483,  0.12420684, -0.83795346])

In [47]:
#균등(Uniform) 분포
np.random.uniform(3,4,4)

array([3.61652471, 3.96384302, 3.57430429, 3.37116085])