# Numpy - Part 2

In [1]:
import numpy as np

### 4.Operation

In [2]:
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [3]:
a.sum()

78

In [4]:
a.sum(axis=0)


array([15, 18, 21, 24])

In [5]:
a.sum(axis = 1)


array([10, 26, 42])

In [6]:
np.sum(a[0])

10

- sorting

In [7]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [8]:
np.sort(b)      #axis = 1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [9]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [10]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [11]:
# 내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42,38,12,25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [12]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [13]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [14]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical functions

In [15]:
def sigmoid(x):
    return 1. / (1+np.exp(-x))

In [16]:
xs = np.array([-10,0,10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

-전치행렬

In [17]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [18]:
b.T

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [19]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [20]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [21]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [24]:
a+a

array([[2, 4],
       [6, 8]])

In [25]:
a-a

array([[0, 0],
       [0, 0]])

In [26]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [27]:
a/a

array([[1., 1.],
       [1., 1.]])

- broadcasting

In [28]:
a+3

array([[4, 5],
       [6, 7]])

-dot product

In [29]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [30]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [31]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [32]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- all % any

In [38]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.any(a>5), np.all(a>5)

(True, False)

In [39]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

-logical operation

In [40]:
b=np.logical_and(a>3,a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [41]:
np.logical_or(a<3, a>7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [43]:
np.argmax(a), np.argmin(a)

(9, 0)

### 6.Boolean & Fancy index

In [45]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [44]:
a[b]

array([4, 5, 6])

In [47]:
a[np.logical_or(a<3,a>7)]

array([0, 1, 2, 8, 9])

In [48]:
a[a>5]

array([6, 7, 8, 9])

In [50]:
a[[3,5,7,3]]

array([3, 5, 7, 3])

### 7.기술 통계

In [68]:
a = np.random.randn(10)
a

array([-0.3340864 , -1.48638038,  2.72654579, -0.20432695,  1.30285048,
       -0.30439583, -0.87092045, -0.04020741,  0.06092653, -0.32885086])

In [52]:
# 평균(Mean)
a.mean(), np.mean(a)

(-0.01836723547608706, -0.01836723547608706)

In [73]:
# 표준 편차 (Standard deviation)
a.std(), np.std(a)

(1.1149722782521172, 1.1149722782521172)

In [55]:
a.max(), a.min()

(0.9516386369242162, -1.407146483928277)

In [59]:
# 4분위수
np.percentile(a,100), np.percentile(a,0)

(0.9516386369242162, -1.407146483928277)

In [58]:
np.percentile(a,25), np.percentile(a,75)

(-0.24016061139987438, 0.38510524615846353)

In [62]:
np.percentile(a,50), np.median(a)

(0.023549722676780155, 0.023549722676780155)

In [76]:
a = np.random.randn(250)
a.std()

1.0030564743603592

AttributeError: 'numpy.ndarray' object has no attribute 'values'