In [1]:
import numpy as np
import random

In [2]:
# 1
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
#강사님
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
#2
m = np.array([[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
#2-1 값7 인덱싱
m[1][2]

7

In [7]:
m[m==7]

array([7])

In [8]:
#2-2 값 14 인덱싱
m[-1][-1] #0차원(값)


14

In [9]:
#배열   [6, 7] 을    슬라이싱
m[1,1:3],m[1:2,1:3]  # 1차원, 2차원

(array([6, 7]), array([[6, 7]]))

In [10]:
#배열   [7, 12] 을    슬라이싱
m[1:,2], m[1:,2:3]

(array([ 7, 12]),
 array([[ 7],
        [12]]))

In [11]:
#[[3, 4], [8, 9]] 을    슬라이싱
m[:2,3:],m[:-1,3:]

(array([[3, 4],
        [8, 9]]),
 array([[3, 4],
        [8, 9]]))

In [12]:
# 3.2번의    행렬    m을    1차원    벡터    f 로    변환한    후    다음의    문제를    푸시오.
f=(m.flatten())#f=m.reshape(-1)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
f = [f % 3==0]
f


[array([ True, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False])]

In [14]:
#3의    배수
f[np.logical_and(f>0,f%3==0)]

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
#4로    나누면    1이    남는    수
f[np.logical_and(f>4,f%4==1)]

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
#3으로   나누면    나누어지고    4로    나누면    1이    남는    수
f[np.logical_and(f%3==0,f%4==1)]

array([9])

In [ ]:
# 4
np.eye(5,5,k = -1)+np.eye(5,5,k = -1)+np.eye(5,5,k = -1)+np.eye(5,5,k = 0)+np.eye(5,5,k = 0)+np.eye(5,5,k = 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [ ]:
np.eye(5,5,-1, int)*3+np.eye(5,5,0 , int)*2+np.eye(5,5,1 ,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [ ]:
#5.0에서    10까지    랜덤   실수값으로    이루어진    5 x 6 형태의    데이터    행렬을    만들고    이    데이터에 대해    다음과    같은   값을    구하시오
a = np.random.randint(0.0,10.0,(5,6))
a.round(4)
a


array([[5, 2, 5, 2, 4, 4],
       [5, 7, 9, 9, 2, 4],
       [4, 2, 8, 7, 8, 0],
       [1, 1, 5, 6, 0, 6],
       [9, 6, 7, 3, 6, 6]])

In [ ]:
#5-1. 전체의    최댓값
np.max(a)

9

In [ ]:
#각    행의    합
a.sum(axis=0)

array([14, 24, 39, 17, 29, 12])

In [ ]:
#각    행의    최댓값
np.max(a,axis=0)

array([5, 7, 9, 6, 9, 5])

In [ ]:
#각    열의    평균
np.mean(a,axis=1).round(4)

array([3.6667, 6.    , 4.8333, 3.1667, 6.1667])

In [ ]:
#각    열의    최솟값
np.min(a,axis=1)

array([0, 1, 0, 0, 0])

In [ ]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [ ]:
m.max()

9.9724

In [ ]:
m.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [ ]:
np.sum(m, axis = 1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [ ]:
m.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [ ]:
m.mean(axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [ ]:
m.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

In [ ]:
#6
b= np.array([[  1,    2,    3,    4], [ 46,   99,  100,   71], [ 81,   59,   90,  100]])
b

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
b[:,np.argsort(b[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
np.sort(b, axis=1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [ ]:
np.sort(b[1:2][::], axis=1)[::][::-1]


array([[ 46,  71,  99, 100]])

In [ ]:
c =np.sort(b[1:2][:], axis=1)
c



array([[ 46,  71,  99, 100]])

In [ ]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [ ]:
indices[::-1]


array([2, 1, 3, 0], dtype=int64)

In [ ]:
score[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
score[:,np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
#7주사위를    100번    던지는    가상    실험을    파이썬으로    작성하고, 던져서    나오는    숫자의    평균을    구하시오.
np.mean(np.random.randint(1,7,100))

3.57

In [ ]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [ ]:
np.mean(dice)

3.7

In [ ]:
# dice array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [ ]:
unique, counts = np.unique(dice, return_counts =True)
dict(zip(unique,counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [ ]:
#가격이    10,000원인    주식이    있다. 이    주식의    일간    수익률(%)은    기댓값이    0%이고    
# 표준편차가    1% 인    표준    정규    분포를    따른다고    하자. 250일    동안의    주가를    무작위로    생성하시오.
np.random.seed(2021)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end = ' ' )

10149 10218 10175 10093 10149 

In [ ]:
#250개
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_list = []
for i in range(250):
    price = np.round(price*(1+rate[i]))
    price_list.append(price)

price_array=np.array(price_list, dtype = np.int32)
price_array[-10:]


array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [ ]:
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250, dtype = int)
for i in range(250):
    price = np.round(price*(1+rate[i]))
    price_array[i] = price

price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [15]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [48]:
score[:,np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])