In [63]:
import numpy as np
import random

In [7]:
# 1
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
#2
m = np.array([[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
#2-1 값7 인덱싱
m[1][2]

7

In [13]:
m[m==7]

array([7])

In [15]:
#2-2 값 14 인덱싱
m[2][-1]


14

In [17]:
#배열   [6, 7] 을    슬라이싱
m[1,1:3]

array([6, 7])

In [19]:
#배열   [7, 12] 을    슬라이싱
m[1:,2]

array([ 7, 12])

In [20]:
#[[3, 4], [8, 9]] 을    슬라이싱
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [33]:
# 3.2번의    행렬    m을    1차원    벡터    f 로    변환한    후    다음의    문제를    푸시오.
mv=m.reshape(-1)

In [41]:
#3의    배수
mv[np.logical_and(mv>0,mv%3==0)]

array([ 3,  6,  9, 12])

In [48]:
#4로    나누면    1이    남는    수
mv[np.logical_and(mv>4,mv%4==1)]

array([ 5,  9, 13])

In [49]:
#3으로   나누면    나누어지고    4로    나누면    1이    남는    수
mv[np.logical_and(mv%3==0,mv%4==1)]

array([9])

In [59]:
# 4
np.eye(5,5,k = -1)+np.eye(5,5,k = -1)+np.eye(5,5,k = -1)+np.eye(5,5,k = 0)+np.eye(5,5,k = 0)+np.eye(5,5,k = 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [61]:
np.eye(5,5,k = -1)*3+np.eye(5,5,k = 0)*2+np.eye(5,5,k = 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [105]:
#5.0에서    10까지    랜덤   실수값으로    이루어진    5 x 6 형태의    데이터    행렬을    만들고    이    데이터에 대해    다음과    같은   값을    구하시오
a = np.random.randint(0.0,10.0,(5,6))
a


array([[7, 7, 0, 4, 5, 7],
       [6, 7, 2, 1, 9, 6],
       [0, 7, 3, 4, 5, 5],
       [9, 6, 7, 8, 2, 0],
       [3, 5, 7, 1, 8, 0]])

In [106]:
#5-1. 전체의    최댓값
np.argmax(a)

10

In [107]:
#각    행의    합
a.sum(axis=0)

array([25, 32, 19, 18, 29, 18])

In [114]:
#각    행의    최댓값
np.max(a,axis=0)

array([9, 7, 7, 8, 9, 7])

In [116]:
#각    열의    평균
np.mean(a,axis=1)

array([5.        , 5.16666667, 4.        , 5.33333333, 4.        ])

In [115]:
#각    열의    최솟값
np.min(a,axis=1)

array([0, 1, 0, 0, 0])

In [121]:
#6
b= np.array([[  1,    2,    3,    4], [ 46,   99,  100,   71], [ 81,   59,   90,  100]])
b

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [154]:
c =np.sort(b, axis=1)[::][::]


In [155]:
c

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [160]:
#7주사위를    100번    던지는    가상    실험을    파이썬으로    작성하고, 던져서    나오는    숫자의    평균을    구하시오.
np.mean(np.random.randint(1,7,101))

3.405940594059406

In [ ]:
#가격이    10,000원인    주식이    있다. 이    주식의    일간    수익률(%)은    기댓값이    0%이고    
# 표준편차가    1% 인    표준    정규    분포를    따른다고    하자. 250일    동안의    주가를    무작위로    생성하시오.
